global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product:8080']
        labels:
          application: 'Product App'
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:8080']
        labels:
          application: 'Order App'
  - job_name: 'inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory:8080']
        labels:
          application: 'Inventory App'
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification:8080']
        labels:
          application: 'Notification App'